### PR TITLE
chore: fix coverage reporting

### LINKED ISSUE #517: Codecov not working in syrupy repo

### PR DESCRIPTION
**Pull request by noahnu**
Close #517

### CODE REVIEW

**Comment by iamogbz** [comment]
Did this fix the github status check issue? Still don't see it.

**Comment by noahnu** [comment]
No, but if you check the codecov website, you'll see it correctly uploaded the coverage and even knows about the passing status checks. It's just not calling the github webhook I assume

**Comment by iamogbz** [comment]
Yeah but it was always uploading correctly even before this change?

**Comment by mcataford** [comment]
@noahnu @iamogbz Fixed it. Turned out to be misconfiguration that wasn't reported anywhere by Codecov. >.> The integration wasn't enabled for the repository, but Codecov still reported that "the webhook is good and everything is peachy", which was a bold-faced lie.

Looks like the integration is only activated for a certain number of repos, I'm going to turn it on for all in the `tophat` org and put this matter to rest.

**Pull request merged**
