### PR TITLE
feat: option to report details of unused snapshots

### LINKED ISSUE #465: Report which snapshots are unused
**Is your feature request related to a problem? Please describe.**

In test suites that are very long, it can be tedious and frustrating to try to find which snapshots are stale/unused after eg many tests are changed. The current report lists how many snapshots were unused, but not which ones. 

**Describe the solution you'd like**

I would like an optional flag that, when provided, will include the locations & names of unused snapshots in the final report.

**Describe alternatives you've considered**

I don't think there's a great alternative. Usually to find out which snapshots have become obsolete, I have to provide the `--snapshot-update` option and look at the generated diff. When syrupy is running as a CI step, this means I have to rerun the test suite locally, which can be very time consuming.

**Additional context**

I would be happy to make a PR to address this issue.

### PR DESCRIPTION
**Pull request by eaculb**
## Description

This PR introduces an additional CLI option that can be invoked to provide details (test name and snapshot location) of unused snapshots.

## Related Issues

- Closes #465, which requested this feature.

## Checklist

- [x] This PR has sufficient documentation.
- [x] This PR has sufficient test coverage.
- [x] This PR title satisfies semantic [convention](https://www.conventionalcommits.org/en/v1.0.0/#summary).

## Additional Comments

Not married to any wording or formatting; I tried to mirror what was already there as closely as possible.
I enjoy using syrupy in my projects! Thanks!

### CODE REVIEW

**Comment by eaculb** [comment]
Hm ok, looks like the Windows VMs ends up with a different order for the unused snapshots? I'll adjust.

**Comment by noahnu** [comment]
This looks great!

I ran the coverage report locally and can confirm it's still reporting 100%. We can probably add a different step for contributors that posts the codecov to the PR directly w/o going through codecov to avoid the token issue.

**Review by noahnu — APPROVED** [review]

**Comment by noahnu** [comment]
@all-contributors add eaculb for code, tests

**Comment by eaculb** [comment]
Thank you & thanks for doing a release! :)

**Comment by eaculb** [comment]
hi @noahnu ! I was just looking to upgrade my `syrupy` version within a project and noticed that `1.2.0` isn't available on pypi -- is this intentional or could the team please make it available? Thank you in advance!

**Comment by noahnu** [comment]
This isn't intentional. I'll take a look. We recently changed the publish process, there might be a regression.

**Comment by eaculb** [comment]
thank you!

**Comment by noahnu** [comment]
@eaculb Sorry about that. Everything should be working now. Latest release is 1.2.2.

**Comment by eaculb** [comment]
No problem -- Thanks so much for fixing!

**Pull request merged**
